name: zcwpw1
channels:
  - bioconda
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - fastqc
  - bedtools
  - samtools
  - htslib
  - bwa
  - bowtie
  - bedops
  - deeptools
  - snakemake=5.5.4
  - picard
  - goleft
  - mosdepth
#  - ucsc-bedgraphtobigwig
  #  - r-essentials
  #  - r-base
