name: zcwpw1
channels:
  - bioconda
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - fastqc
  - bedtools
  - samtools
  - htslib
  - bwa
  - bowtie
  - bedops
  - deeptools
  - snakemake
  - picard
  - goleft
  - mosdepth
  - ucsc-bedgraphtobigwig
  #  - r-essentials
  #  - r-base
