---
title: "Alu Align"
output: html_notebook
---

# Aligned Alu CpG

multi-align AluJo sequences with each other (as variable poly A in center messes things up otherwise - see histogram above). The compare aligned positions for diff in frequency of CpG

## Using ensembl kalign

```{r}

overlap_idx <- which(repeatsAlu$Name=="AluJo" & repeatsAlu$overlap==T)[1:1000]
nonoverlap_idx <- which(repeatsAlu$Name=="AluJo" & repeatsAlu$overlap==F)[1:1000]
tmp <- AluRepeats[c(overlap_idx, nonoverlap_idx)]
names(tmp) <- paste0(seq_along(tmp),"_", names(tmp))
export_FASTA(tmp, "AluJo.fasta")

AluAligned <- seqinr::read.fasta("../data/kalign-I20190715-002019-0175-34958881-p2m.fasta", forceDNAtolower = FALSE, as.string = TRUE)
AluAligned <- unlist(AluAligned)

AluAlignedM <- matrix(ncol=nchar(AluAligned[1]), unlist(strsplit(AluAligned,"")), byrow=T)

nongaps <- apply(AluAlignedM, 2, function(x) sum(x=="-"))<200
AluAlignedM <- AluAlignedM[,nongaps]

# c_o <- apply(AluAlignedM[1:1000,], 2, function(x) mean(x=="c"))
# c_no <- apply(AluAlignedM[1001:2000,], 2, function(x) mean(x=="c"))
# 
# plot(log(c_o/c_no))

CG_locations_aligned <- sapply(AluAligned,function(x) stringr::str_locate_all(x,"c(-+)?g")[[1]][,1])

hist(unlist(CG_locations_aligned[1:1000]), breaks=5000, xlim=c(0,max(unlist(CG_locations_aligned))), ylim=c(0,175))
hist(unlist(CG_locations_aligned[1001:2000]), breaks=5000, xlim=c(0,max(unlist(CG_locations_aligned))), ylim=c(0,175))

o_v_no <- rbind(data.table(table(unlist(CG_locations_aligned[1:1000])), type="overlaping"),
                data.table(table(unlist(CG_locations_aligned[1001:2000])), type="nonOverlaping"))

o_v_no_cast <- dcast(o_v_no, V1 ~ type, value.var = "N", fill = 0)
o_v_no_cast[, OvsNOratio := (overlaping+30) / (nonOverlaping+30)]

ggplot(o_v_no_cast, aes(as.numeric(V1), OvsNOratio)) + geom_point() + labs(x="Aligned Position in Alu repeat", y="Ratio of CpG counts in Zcw overlaping Alus vs non-overlaping")

o_v_no_cast[order(-OvsNOratio)][1:20]
o_v_no_cast[order(OvsNOratio)][1:20]
```

## Using R msa

```{r}

tmp <- toupper(AluRepeats[c(overlap_idx[1:1000], nonoverlap_idx[1:1000])])
names(tmp) <- paste0(seq_along(tmp),"_", names(tmp))

AluOverlapAlign <- msa(tmp, type="dna", order="input")
AluOverlapAlignChar <- as.character(AluOverlapAlign)

CG_locations_aligned2 <- sapply(AluOverlapAlignChar,function(x) stringr::str_locate_all(x,"C(-+)?G")[[1]][,1])

hist(unlist(CG_locations_aligned2[1:1000]), breaks=5000, xlim=c(0,max(unlist(CG_locations_aligned2))), ylim=c(0,225))
hist(unlist(CG_locations_aligned2[1:2000]), breaks=5000, xlim=c(0,max(unlist(CG_locations_aligned2))), ylim=c(0,225))

o_v_no <- rbind(data.table(table(unlist(CG_locations_aligned2[1:1000])), type="overlaping"),
                data.table(table(unlist(CG_locations_aligned2[1001:2000])), type="nonOverlaping"))

o_v_no_cast <- dcast(o_v_no, V1 ~ type, value.var = "N", fill = 0)
o_v_no_cast[, OvsNOratio := (overlaping+30) / (nonOverlaping+30)]

ggplot(o_v_no_cast, aes(as.numeric(V1), OvsNOratio)) + geom_point() + labs(x="Aligned Position in Alu repeat", y="Ratio of CpG counts in Zcw overlaping Alus vs non-overlaping")

o_v_no_cast[order(-OvsNOratio)][1:20]
o_v_no_cast[order(OvsNOratio)][1:20]
```

## Try to align everything to reference.

```{r}
library(Biostrings)

AluJo <- "GGCCGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGAGGATCGCTTGAGCCCAGGAGTTCGAGACCAGCCTGGGCAACATAGCGAGACCCCGTCTCTACAAAAAATACAAAAATTAGCCGGGCGTGGTGGCGCGCGCCTGTAGTCCCAGCTACTCGGGAGGCTGAGGCGGGAGGATCGCTTGAGCCCAGGAGNTCGAGGCTGCAGTGAGCTATGATCGCGCCACTGCACTCCAGCCTGGGCGACAGAGCGAGACCCTGTCTCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

sapply( seq2, function(x) pairwiseAlignment(toupper(c2s(x)), seq1string)) )

tmp <- pairwiseAlignment(toupper(AluRepeats[overlap_idx][1:3]), AluJo, type="overlap")
toString(subject(tmp))
toString(pattern(tmp))
nchar(strsplit(toString(pattern(tmp)), ", ")[[1]])
nchar(strsplit(toString(subject(tmp)), ", ")[[1]])
```
