---
title: "DMC1 Hotspots"
output: html_notebook
---

dmc1hotspots in PWD x B6 F1
either PRDM9 Humanised or PRDM9 B6 allele

# DMC1 Hotspots

```{r download_hotspots}
wget -P ../data ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2049nnn/GSM2049308/suppl/GSM2049308%5Fdmc1hotspots%5FPWDB6F1%2EPRDM9pb%2Etxt%2Egz
wget -P ../data ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2049nnn/GSM2049309/suppl/GSM2049309%5Fdmc1hotspots%5FPWDB6F1%2EPRDM9ph%2Etxt%2Egz

library(data.table)
ph <- fread("zcat < ../data/GSM2049309_dmc1hotspots_PWDB6F1.PRDM9ph.txt.gz")
pb <- fread("zcat < ../data/GSM2049308_dmc1hotspots_PWDB6F1.PRDM9pb.txt.gz")
```

```{r hotspots_to_bed}

library(ggplot2)

str(pb)
str(ph)


pb[,Chr := paste0("chr",chr)]
ph[,Chr := paste0("chr",chr)]

ggplot(pb[dmc1_heat>100], aes(b6ratio, fill=origin)) + geom_histogram()
ggplot(ph[dmc1_heat>100], aes(b6ratio, fill=origin)) + geom_histogram()
ggplot(pb, aes(b6ratio, fill=origin)) + geom_histogram()
ggplot(ph, aes(b6ratio, fill=origin)) + geom_histogram()


fwrite(pb[,.(Chr, pos, pos+1, origin, b6ratio, dmc1_heat)][order(-dmc1_heat)],
       "../data/dmc1hotspots_PWDB6F1.PRDM9pb.bed", col.names = FALSE, sep = "\t")
fwrite(ph[,.(Chr, pos, pos+1, origin, b6ratio, dmc1_heat)][order(-dmc1_heat)],
       "../data/dmc1hotspots_PWDB6F1.PRDM9ph.bed", col.names = FALSE, sep = "\t")
#dmc1_heat>100 &

fwrite(pb[ origin=="B6",.(Chr, pos, pos+1, origin, b6ratio, dmc1_heat)][order(-dmc1_heat)], 
       "../data/dmc1hotspots_PWDB6F1.PRDM9pb_B6.bed", col.names = FALSE, sep = "\t")
fwrite(pb[ origin=="PWD",.(Chr, pos, pos+1, origin, b6ratio, dmc1_heat)][order(-dmc1_heat)], 
       "../data/dmc1hotspots_PWDB6F1.PRDM9pb_PWD.bed", col.names = FALSE, sep = "\t")
fwrite(pb[ origin!="PWD" & origin!="B6",.(Chr, pos, pos+1, origin, b6ratio, dmc1_heat)][order(-dmc1_heat)], 
       "../data/dmc1hotspots_PWDB6F1.PRDM9pb_Other.bed", col.names = FALSE, sep = "\t")

fwrite(ph[ origin=="HUM",.(Chr, pos, pos+1, origin, b6ratio, dmc1_heat)][order(-dmc1_heat)], 
       "../data/dmc1hotspots_PWDB6F1.PRDM9ph_HUM.bed", col.names = FALSE, sep = "\t")
fwrite(ph[ origin=="PWD",.(Chr, pos, pos+1, origin, b6ratio, dmc1_heat)][order(-dmc1_heat)], 
       "../data/dmc1hotspots_PWDB6F1.PRDM9ph_PWD.bed", col.names = FALSE, sep = "\t")
fwrite(ph[ origin!="PWD" & origin!="B6",.(Chr, pos, pos+1, origin, b6ratio, dmc1_heat)][order(-dmc1_heat)], 
       "../data/dmc1hotspots_PWDB6F1.PRDM9ph_Other.bed", col.names = FALSE, sep = "\t")

```
