---
title: "DMC1 Counts"
output: html_notebook
---

```{r}
knitr::opts_knit$set(base.dir = "results")
knitr::opts_chunk$set(fig.path = "non_ChIP/")
knitr::opts_chunk$set(dev="pdf")
knitr::opts_chunk$set(fig.show="hold")

library(data.table)
library(ggplot2)
library(ggsignif)
#library(readxl)
#library(Hmisc)
library(cowplot)
```

```{r}
# convert 2e4 etc. to scientific notation
fs <- function(l) {
     # turn in to character string in scientific notation
     l <- format(l, scientific = TRUE)
     # quote the part before the exponent to keep all the digits
     l <- gsub("^(.*)e", "'\\1'e", l)
     # turn the 'e+' into plotmath format
     l <- gsub("e", "%*%10^", l)
     # return this as an expression
     return(l)
}
```


```{r load_DMC1}

# # # # # # # # # # # #
# Load KO counts
# # # # # # # # # # # #

dmc1_counts_KO <- readxl::read_excel("../data/cellular/zcw_dmc1.xlsx", sheet = "KO")
dmc1_counts_KO$...4 <- colnames(dmc1_counts_KO)[1]
dmc1_counts_KO$...10 <- colnames(dmc1_counts_KO)[7]
dmc1_counts_KO$...14 <- colnames(dmc1_counts_KO)[11]

colnames(dmc1_counts_KO) <- unlist(dmc1_counts_KO[1,])
colnames(dmc1_counts_KO)[c(4,10,14)] <- "Mouse"

dmc1_counts_KO <- rbind(dmc1_counts_KO[,1:4],
                     dmc1_counts_KO[,7:10],
                     dmc1_counts_KO[,11:14])

dmc1_counts_KO$Genotype <- "Zcwpw1 -/-"

# # # # # # # # # # # #
# Load WT counts
# # # # # # # # # # # #


dmc1_counts_WT <- readxl::read_excel("../data/cellular/zcw_dmc1.xlsx", sheet = "WT")

dmc1_counts_WT$...4 <- colnames(dmc1_counts_WT)[1]
dmc1_counts_WT$...8 <- colnames(dmc1_counts_WT)[5]

colnames(dmc1_counts_WT) <- unlist(dmc1_counts_WT[1,])
colnames(dmc1_counts_WT)[c(4,8)] <- "Mouse"

dmc1_counts_WT <- rbind(dmc1_counts_WT[,1:4],
                     dmc1_counts_WT[,5:8])

dmc1_counts_WT$Genotype <- "Wild Type"

# # # # # # # # # # # #
# Load P9 KO counts
# # # # # # # # # # # #

dmc1_counts_P9 <- readxl::read_excel("../data/cellular/zcw_dmc1.xlsx", sheet = "Prdm9 KO", skip=1)

# # add mouse ID column
# dmc1_counts_P9$...4 <- colnames(dmc1_counts_P9)[1]
# 
# colnames(dmc1_counts_P9) <- unlist(dmc1_counts_P9[1,])
# colnames(dmc1_counts_P9)[c(4)] <- "Mouse"

dmc1_counts_P9$Mouse <- "TGFJ 27.1B (6 Aug 2019)"
dmc1_counts_P9$Genotype <- "Prdm9 -/-"


dmc1_counts_P9B <- readxl::read_excel("../data/cellular/Second prdm9 KO DMC1 foci.xlsx", skip = 1)
dmc1_counts_P9B$Mouse <- "TGFJ 26.2C (11Oct 2019)"
dmc1_counts_P9B$Genotype <- "Prdm9 -/-"

# # # # # # # # # # # #
# Unrelated WT counts
# # # # # # # # # # # #

dmc1_counts_UWT <- readxl::read_excel("../data/cellular/zcw_dmc1.xlsx", sheet = "Unrelated wt")
dmc1_counts_UWT$...4 <- colnames(dmc1_counts_UWT)[1]
dmc1_counts_UWT$...9 <- colnames(dmc1_counts_UWT)[6]
dmc1_counts_UWT$...13 <- colnames(dmc1_counts_UWT)[10]

colnames(dmc1_counts_UWT) <- unlist(dmc1_counts_UWT[1,])
colnames(dmc1_counts_UWT)[c(4,9,13)] <- "Mouse"

dmc1_counts_UWT <- rbind(dmc1_counts_UWT[,1:4],
                     dmc1_counts_UWT[,6:9],
                     dmc1_counts_UWT[,10:13])

colnames(dmc1_counts_UWT)[1] <- "Image"
colnames(dmc1_counts_UWT)[3] <- "DMC1 foci"

dmc1_counts_UWT$Genotype <- "Wild Type (unrelated)"


# # # # # # # # # # # #
# Combine & Plot
# # # # # # # # # # # #

dmc1_counts <- rbind(dmc1_counts_KO,
                     #dmc1_counts_WT,
                     dmc1_counts_P9,
                     dmc1_counts_P9B,
                     dmc1_counts_UWT)

dmc1_counts <- dmc1_counts[!(toupper(dmc1_counts$Image)=="IMAGE"),]

names(dmc1_counts)[names(dmc1_counts)=="DMC1 foci"] <- "Foci"

dmc1_counts$Foci <- as.integer(dmc1_counts$Foci)


dmc1_counts <- dmc1_counts[!is.na(dmc1_counts$Stage),]

dmc1_counts$Stage <- stringr::str_to_title(dmc1_counts$Stage)

dmc1_counts[dmc1_counts$Stage=="L",]$Stage <- "Late L"
dmc1_counts[dmc1_counts$Stage=="P",]$Stage <- "(Pseudo) P"
dmc1_counts[dmc1_counts$Stage=="P?",]$Stage <- "(Pseudo)P"
dmc1_counts[dmc1_counts$Stage=="Pseudop",]$Stage <- "(Pseudo)P"
dmc1_counts[dmc1_counts$Stage=="Z",]$Stage <- "Mid Z"

dmc1_counts[dmc1_counts$Genotype=="Wild Type (unrelated)",]$Genotype <- "Wild Type"

dmc1_counts$Stage <- factor(dmc1_counts$Stage, levels = c("L","Late L","Early Z","Mid Z","Late Z","(Pseudo)P","P?","Pseudop"))
dmc1_counts$Genotype <- factor(dmc1_counts$Genotype, levels = c("Wild Type","Wild Type (unrelated)","Zcwpw1 -/-","Prdm9 -/-"))
```

```{r dmc1_counts, fig.width=7, fig.height=5, fig.retina=T}
p <- ggplot(dmc1_counts, aes(Stage, Foci, colour=Genotype)) + 
  geom_point(size=0.5, position = position_jitterdodge()) + 
  scale_color_brewer(palette = "Set1", labels = c("Wild Type",expression(italic("Zcwpw1")^"-/-"),expression(italic("Prdm9")^"-/-"))) + 
  theme_minimal() + 
  geom_boxplot(alpha=0) +
  theme(legend.position = "bottom") +
  ylab("DMC1 Foci Count")


# check by mouse
ggplot(dmc1_counts, aes(Stage, Foci, colour=Mouse)) + geom_jitter() + facet_wrap(~Genotype)

ggplot(data.table(dmc1_counts)[Genotype=="Prdm9 -/-"], aes(Stage, Foci, colour=Mouse, group=Mouse)) + 
  geom_jitter(position = position_jitterdodge())

# add pvalues
for(stage in c("Late L","Early Z","Mid Z","Late Z","(Pseudo)P")){
print(t.test(data.table(dmc1_counts)[Genotype=="Zcwpw1 -/-" & Stage ==stage]$Foci,
       data.table(dmc1_counts)[Genotype=="Wild Type" & Stage ==stage]$Foci))
}

p + geom_signif(y_position=c(80, 290, 325, 220, 230),
                xmin=c(0.7, 1.7, 2.7, 3.7, 4.7),
                xmax=c(1, 2, 3, 4, 5),
              annotation=c("0.5",fs("2.0e-3"),fs("6.0e-10"),fs("1.2e-06"),fs("3.3e-52")),
              tip_length=0.01, col="black", parse=TRUE) + ylim(0,330)

#ggsave("../results/dmc1_counts.pdf", width = 7, height = 5)
```

```{r load_rad51}
# # # # # # # # # # # #
# KO
# # # # # # # # # # # #

rad51_counts_ZCW <- readxl::read_excel("../data/cellular/Rad51.xlsx", sheet = "ZCW KO")

rad51_counts_ZCW$Mouse1 <- colnames(rad51_counts_ZCW)[1]
rad51_counts_ZCW$Mouse2 <- colnames(rad51_counts_ZCW)[5]

rad51_counts_ZCW <- rad51_counts_ZCW[2:nrow(rad51_counts_ZCW),]

colnames(rad51_counts_ZCW) <- c("Image","Stage","Foci","NA1","NA2","Image","Stage","Foci","Mouse","Mouse")

rad51_counts_ZCW <- rbind(rad51_counts_ZCW[,c(1:3,9)],
                     rad51_counts_ZCW[,c(6:8,10)])

rad51_counts_ZCW$Genotype <- "Zcwpw1 KO"

# # # # # # # # # # # #
# Prdm9KO counts
# # # # # # # # # # # #

rad51_counts_P9KO <- readxl::read_excel("../data/cellular/Rad51.xlsx", sheet = "Prdm9 KO")

rad51_counts_P9KO$Mouse <- colnames(rad51_counts_P9KO)[1]
rad51_counts_P9KO <- rad51_counts_P9KO[2:nrow(rad51_counts_P9KO),]

colnames(rad51_counts_P9KO) <- c("Image","Stage","Foci","Mouse")

rad51_counts_P9KO$Genotype <- "Prdm9 KO"


# # # # # # # # # # # #
# WT counts
# # # # # # # # # # # #

rad51_counts_WT <- readxl::read_excel("../data/cellular/Rad51.xlsx", sheet = "Wt unrelated")

rad51_counts_WT$Mouse1 <- colnames(rad51_counts_WT)[1]
rad51_counts_WT$Mouse2 <- colnames(rad51_counts_WT)[6]

rad51_counts_WT <- rad51_counts_WT[2:nrow(rad51_counts_WT),]

colnames(rad51_counts_WT) <- c("Image","Stage","Foci","NA1","NA2","Image","Stage","Foci","Mouse","Mouse")

rad51_counts_WT <- rbind(rad51_counts_WT[,c(1:3,9)],
                     rad51_counts_WT[,c(6:8,10)])

rad51_counts_WT$Genotype <- "WT"


# # # # # # # # # # # #
# Plot
# # # # # # # # # # # #

rad51_counts <- data.table(rbind(rad51_counts_WT, rad51_counts_P9KO, rad51_counts_ZCW))[!is.na(Foci)]

rad51_counts$Foci <- as.integer(rad51_counts$Foci)

rad51_counts[rad51_counts$Stage=="late Z",]$Stage <- "Late Z"
rad51_counts[rad51_counts$Stage=="Z",]$Stage <- "Mid Z"
rad51_counts[rad51_counts$Stage=="PseudoP",]$Stage <- "(Pseudo)P"
rad51_counts[rad51_counts$Stage=="P",]$Stage <- "(Pseudo)P"

rad51_counts$Stage <- factor(rad51_counts$Stage, levels = c("L","Late L","Early Z","Mid Z","Late Z","(Pseudo)P","Late P"))
rad51_counts$Genotype <- factor(rad51_counts$Genotype, levels = c("WT","Zcwpw1 KO","Prdm9 KO"))

for(stage in c("Late L","Early Z","Mid Z","Late Z","(Pseudo)P")){
print(t.test(data.table(rad51_counts)[Genotype=="Zcwpw1 KO" & Stage ==stage]$Foci,
       data.table(rad51_counts)[Genotype=="WT" & Stage ==stage]$Foci))
}
```


```{r rad51_counts, fig.width=7, fig.height=5}
p <- ggplot(rad51_counts[Stage!="Late P" & Stage!="L"], aes(Stage, Foci, colour=Genotype)) + 
  geom_point(size=0.5, position = position_jitterdodge()) + 
  scale_color_brewer(palette = "Set1", labels = c("Wild Type",expression(italic("Zcwpw1")^"-/-"),expression(italic("Prdm9")^"-/-"))) + 
  theme_minimal() + 
  geom_boxplot(alpha=0) +
  theme(legend.position = "bottom") +
  ylab("RAD51 Foci Count")

p + geom_signif(y_position=c(110, 210, 270, 130, 100),
                xmin=c(0.7, 1.7, 2.7, 3.7, 4.7),
                xmax=c(1, 2, 3, 4, 5),
              annotation=c("0.12",fs("0.06"),fs("0.04"),fs("0.08"),fs("1.9e-14")),
              tip_length=0.01, col="black", parse=TRUE) + ylim(0,280)

p

#ggsave("../results/rad51_counts.pdf", width = 7, height = 5)
```

```{r load_RPA}

rpa_counts_ZCW <- readxl::read_excel("../data/cellular/RPA.xlsx")

rpa_counts_ZCW$Mouse1 <- colnames(rpa_counts_ZCW)[1]
rpa_counts_ZCW$Mouse2 <- colnames(rpa_counts_ZCW)[8]
rpa_counts_ZCW$Mouse3 <- colnames(rpa_counts_ZCW)[13]

rpa_counts_ZCW <- rpa_counts_ZCW[2:nrow(rpa_counts_ZCW),]

colnames(rpa_counts_ZCW) <- c("Image","Stage","Foci","NA1","NA2","NA3","NA4","Image","Stage","Foci","NA5","NA6","Image","Stage","Foci","NA7","NA8","NA9","NA10","NA11","NA12","NA13","Mouse","Mouse","Mouse")

rpa_counts <- data.table(rbind(rpa_counts_ZCW[,c(1:3,23)],
                     rpa_counts_ZCW[,c(8:10,24)],
                     rpa_counts_ZCW[,c(13:15,25)]))

rpa_counts[grep("TG",Mouse), Genotype := "WT"]
rpa_counts[grep("ZCWP",Mouse), Genotype := "Zcwpw1 KO"]

rpa_counts[rpa_counts$Stage=="lateZ",]$Stage <- "Late Z"
rpa_counts[rpa_counts$Stage=="LateZ",]$Stage <- "Late Z"
rpa_counts[rpa_counts$Stage=="EarlyZ",]$Stage <- "Early Z"
rpa_counts[rpa_counts$Stage=="Mid Z",]$Stage <- "Mid Z"
rpa_counts[rpa_counts$Stage=="P",]$Stage <- "(Pseudo)P"
rpa_counts[rpa_counts$Stage=="PseudoP",]$Stage <- "(Pseudo)P"
rpa_counts <- rpa_counts[!is.na(Image)]

rpa_counts$Stage <- factor(rpa_counts$Stage, levels = c("L","Late L","Early Z","Mid Z","Late Z","(Pseudo)P","Late P"))
rpa_counts$Genotype <- factor(rpa_counts$Genotype, levels = c("WT","Zcwpw1 KO","Prdm9 KO"))
rpa_counts[, Foci := as.numeric(Foci)]


for(stage in c("Early Z","Mid Z","Late Z","(Pseudo)P")){
print(t.test(data.table(rpa_counts)[Genotype=="Zcwpw1 KO" & Stage ==stage]$Foci,
       data.table(rpa_counts)[Genotype=="WT" & Stage ==stage]$Foci))
}
```


```{r rpa_counts, fig.width=7, fig.height=5}
p <- ggplot(rpa_counts[Stage!="Late L"], aes(Stage, Foci, colour=Genotype)) + 
  geom_point(size=0.5, position = position_jitterdodge()) + 
  scale_color_brewer(palette = "Set1", labels = c("Wild Type",expression(italic("Zcwpw1")^"-/-"),expression(italic("Prdm9")^"-/-"))) + 
  theme_minimal() + 
  geom_boxplot(alpha=0) +
  theme(legend.position = "bottom") +
  ylab("RPA Foci Count")

p + geom_signif(y_position=c(350, 400, 320, 250),
                xmin=c(0.8, 1.8, 2.8, 3.8),
                xmax=c(1.2, 2.2, 3.2, 4.2),
              annotation=c("0.097",fs("4.41e-05"),fs("0.0014"),fs("< 2.2e-16")),
              tip_length=0.01, col="black", parse=TRUE) + ylim(0,420)

p

#ggsave("../results/rpa_counts.pdf", width = 7, height = 5)
```

```{r export_data}
dmc1_counts$Target <- "DMC1"
rad51_counts$Target <- "RAD51"
rpa_counts$Target <- "RPA2"

fwrite(rbind(dmc1_counts, rad51_counts, rpa_counts), "../results/non_ChIP/DMC1_RAD51_RPA2_Counts.csv")

```



```{r synapsis}
synapsis <- data.table(Synapsis = c(0.98,0.94,0.946,0.02,0.00,0.019,0.054,0.06),
           n = c(51L,52L,56L,51L,51L,53L,55L,49L),
           Genotype = c("WT","WT","WT","Zcwpw1-/-","Zcwpw1-/-","Zcwpw1-/-","Prdm9-/-","Prdm9-/-"))

synapsis[,infered_sucess := round(Synapsis*n)]

synapsis[, Genotype := factor(Genotype, levels=c("WT","Zcwpw1-/-","Prdm9-/-"))]

# not for small n!
# synapsis[, sep := sqrt( (Synapsis * (1 - Synapsis)) / n)]

synapsis <- cbind(synapsis,
                  data.table(Hmisc::binconf(synapsis$infered_sucess, synapsis$n, method="wilson")))

ps <- ggplot(synapsis, aes(Genotype, Synapsis)) +
  geom_pointrange(aes(ymin = Lower, ymax = Upper), position = position_dodge2(width = 0.5)) +
  theme_minimal() +
  ylab("Full Synapsis") +
  theme(axis.line=element_line()) +
  scale_y_continuous(labels = scales::percent)
  #scale_size_area(name="n (cells)", max_size = 3)

ps <- ps + scale_x_discrete(labels=c("WT",expression(italic("Zcwpw1")^"-/-"),expression(italic("Prdm9")^"-/-")))

```


```{r weights}
weights <- data.table(lean_body_weight=c(19.7,21.98,19.8,20.42,22.56,20.66, 18.89, 19.62, 21.77, 22.36),
           paired_testes_weight=c(35,56.9,179.2,183.8,190.4,49.8, 39.4, 50.9, 50.3, 49.2),
           Genotype=c("Zcwpw1-/-","Zcwpw1-/-","WT","WT","WT","Zcwpw1-/-","Zcwpw1-/-","Zcwpw1-/-", "Prdm9-/-", "Prdm9-/-"))

weights[,ratio := paired_testes_weight/lean_body_weight]

weights[, Genotype := factor(Genotype, levels=c("WT","Zcwpw1-/-","Prdm9-/-"))]

str(t.test(weights[Genotype=="Zcwpw1-/-"]$ratio, weights[Genotype=="WT"]$ratio))

pw <-ggplot(weights, aes(Genotype, ratio)) + 
  geom_jitter(position = position_dodge2(width = 0.5)) +
  theme_minimal() +
  ylab("mg of testes per gram of lean body weight") +
  geom_signif(comparisons = list(c("Zcwpw1-/-","WT")),
              test="t.test",
              map_signif_level = function(x) paste0("p = ",signif(x,2)),
              margin_top = 0.1) +
  theme(axis.line=element_line()) +
  scale_y_continuous(expand = c(0, 0), limits=c(0,11))
pw

pw <- pw + scale_x_discrete(labels=c("WT",expression(italic("Zcwpw1")^"-/-"),expression(italic("Prdm9")^"-/-")))

```

```{r weights_&_synapsis, fig.width=3, fig.height=7}

cowplot::plot_grid(pw, ps, nrow=2)
#ggsave("../results/weight_&_synapsis.pdf", width = 3, height = 7)
```

