---
title: "FC 100bp Windows"
output: html_notebook
---

Count CpG per 100bp window

```{r}
bedtools intersect -a forcepeaks/genome.windows.100wide.100slide.bed -b CpG_hg38_cut.bed -c > CpG_hg38_100bpwindows.bed
```


# Load data

just using Chromosome 1, as many data points

```{r}
library(data.table)
library(ggplot2)
library(cowplot)

#grep -P 'chr1\\t|chr\\t' 

CpG_100bp <- fread("CpG_hg38_100bpwindows.bed")

h3k4me3_UT_100bp <- fread("peaks/ForceCalledPeaks_NA15-SRR5627150_vs_NA15-SRR5627142_AT_genome.windows.100wide.100slide.bed.bed")
h3k4me3_hP9_100bp <- fread("peaks/ForceCalledPeaks_NA15-SRR5627152_AND_NA15-SRR5627153_vs_NA15-SRR5627143_AT_genome.windows.100wide.100slide.bed.bed")

h3k36me3_hP9_100bp <- fread("peaks/ForceCalledPeaks_NA15-SRR5627149_vs_NA15-SRR5627143_AT_genome.windows.100wide.100slide.bed.bed")


zcw_100bp <- fread("peaks/ForceCalledPeaks_WTCHG_538916_221156_vs_WTCHG_538916_217108_AND_WTCHG_538916_220144_AT_genome.windows.100wide.100slide.bed.bed")

zcw_hP9_100bp <- fread("peaks/ForceCalledPeaks_WTCHG_538916_223180_vs_WTCHG_538916_217108_AND_WTCHG_538916_220144_AT_genome.windows.100wide.100slide.bed.bed")

zcw_cP9_100bp <- fread("peaks/ForceCalledPeaks_WTCHG_538916_224192_vs_WTCHG_538916_217108_AND_WTCHG_538916_220144_AT_genome.windows.100wide.100slide.bed.bed")

zcw_hCVC <- fread("peaks/ForceCalledPeaks_WTCHG_538916_223180_vs_WTCHG_538916_221156_AT_genome.windows.100wide.100slide.bed.bed")

zcw_cCVC <- fread("peaks/ForceCalledPeaks_WTCHG_538916_224192_vs_WTCHG_538916_221156_AT_genome.windows.100wide.100slide.bed.bed")


hP9combo <- fread("peaks/ForceCalledPeaks_NA15-SRR5627146_AND_NA15-SRR5627147_vs_NA15-SRR5627143_AT_genome.windows.100wide.100slide.bed.bed")

cP9combo <- fread("peaks/ForceCalledPeaks_NA15-SRR5627145_AND_NA15-SRR5627144_vs_NA15-SRR5627143_AT_genome.windows.100wide.100slide.bed.bed")

# CAREFULL WITH ORDERING WHEN ADDING NEW COLUMNS!

stopifnot(sum(diff(forcecalled$center_start)<100)==0)

forcecalled <- h3k4me3_UT_100bp

forcecalled$h3k4me3_UT <- forcecalled$enrichment
forcecalled$h3k4me3_UT_enrichment <- forcecalled$h3k4me3_UT
forcecalled$h3k4me3_UT_reads <- forcecalled[,cov_r1 + cov_r2]
forcecalled$h3k4me3_UT_cov_input <- forcecalled$cov_input
forcecalled$h3k4me3_UT_pvalue <- forcecalled$pvalue

forcecalled$CpG <- CpG_100bp[V1 %in% paste0("chr",c(1:22,"X"))]$V4

forcecalled$h3k4me3_hP9_enrichment <- h3k4me3_hP9_100bp$enrichment
forcecalled$h3k4me3_hP9_reads <- h3k4me3_hP9_100bp[,cov_r1 + cov_r2]
forcecalled$h3k4me3_hP9_cov_input <- h3k4me3_hP9_100bp$cov_input
forcecalled$h3k4me3_hP9_pvalue <- h3k4me3_hP9_100bp$pvalue

forcecalled$zcw_enrichment <- zcw_100bp$enrichment
forcecalled$zcw_pvalue <- zcw_100bp$pvalue
forcecalled$zcw_cov_input <- zcw_100bp$cov_input

forcecalled$zcw_hP9_enrichment <- zcw_hP9_100bp$enrichment
forcecalled$zcw_hP9_reads <- zcw_hP9_100bp[,cov_r1 + cov_r2]
forcecalled$zcw_hP9_pvalue <- zcw_hP9_100bp$pvalue
#forcecalled$zcw_P9_cov_input <- zcw_hP9_100bp$cov_input # identical to zcw

forcecalled$zcw_cP9_enrichment <- zcw_cP9_100bp$enrichment
forcecalled$zcw_cP9_pvalue <- zcw_cP9_100bp$pvalue

forcecalled$zcw_hCVC_enrichment <- zcw_hCVC$enrichment
forcecalled$zcw_cCVC_enrichment <- zcw_cCVC$enrichment

forcecalled$hP9combo_enrichment <- hP9combo$enrichment
forcecalled$hP9combo_cov_input <- hP9combo$cov_input
forcecalled$hP9combo_pvalue <- hP9combo$pvalue


forcecalled$cP9combo_enrichment <- cP9combo$enrichment
forcecalled$cP9combo_cov_input <- cP9combo$cov_input
forcecalled$cP9combo_pvalue <- cP9combo$pvalue


forcecalled$h3k36me3_hP9_enrichment <- h3k36me3_hP9_100bp$enrichment
forcecalled$h3k36me3_hP9_cov_input <- h3k36me3_hP9_100bp$cov_input
forcecalled$h3k36me3_hP9_pvalue <- h3k36me3_hP9_100bp$pvalue

sum(forcecalled$center_start!=h3k36me3_hP9_100bp$center_start)
stopifnot(sum(diff(forcecalled$center_start)<100)==0)



```


# Dependence of transfected Zcw on UT

```{r}
# plot(forcecalled$zcw_enrichment,forcecalled$zcw_hP9_enrichment, pch=".", log="xy")
# plot(forcecalled$zcw_enrichment,forcecalled$zcw_hP9_enrichment, pch=".")

# nb intercept doesn't move
fclm <- lm(zcw_hP9_enrichment ~ 1 + zcw_enrichment + hP9combo_enrichment, forcecalled[zcw_cov_input>5])
summary(fclm)

fclm <- lm(zcw_hP9_enrichment ~ 0 + zcw_enrichment + zcw_enrichment:hP9combo_enrichment, forcecalled[zcw_cov_input>5])
summary(fclm)

plot(fclm)

fclm2 <- lm(log(zcw_hP9_enrichment+0.1) ~ log(zcw_enrichment+0.1), forcecalled[zcw_cov_input>5])
plot(fclm2)

####
# Counts
####

# count hP9
cHP9 <- ggplot(forcecalled[zcw_cov_input>5], (aes(zcw_enrichment, zcw_hP9_enrichment))) +
  geom_hex(aes(fill = stat(log(count+0.1))), bins=200) +
  scale_fill_viridis_c(direction = -1) +
  theme(legend.position = "bottom")

  
# count cP9
cCP9 <- ggplot(forcecalled[zcw_cov_input>5], (aes(zcw_enrichment, zcw_cP9_enrichment))) +
  geom_hex(aes(fill = stat(log(count+0.1))), bins=200) +
  scale_fill_viridis_c(direction = -1) +
  theme(legend.position = "bottom")

####
# Color by P9 enrichment
####

# hP9 colour
p1 <- ggplot(forcecalled[zcw_cov_input>5], (aes(zcw_enrichment, zcw_hP9_enrichment, z=log(hP9combo_enrichment+0.1)))) +
  stat_summary_hex(bins=200) +
  scale_fill_viridis_c(name = "log(hP9+0.1)", direction = -1) +
  theme(legend.position = "bottom")

# cP9 colour
p2 <- ggplot(forcecalled[zcw_cov_input>5], (aes(zcw_enrichment, zcw_hP9_enrichment, z=log(cP9combo_enrichment+0.1)))) +
  stat_summary_hex(bins=200) +
  scale_fill_viridis_c(name = "log(cP9+0.1)", direction = -1) +
  theme(legend.position = "bottom")

# hP9 colour
p3 <- ggplot(forcecalled[zcw_cov_input>5], (aes(zcw_enrichment, zcw_cP9_enrichment, z=log(hP9combo_enrichment+0.1)))) +
  stat_summary_hex(bins=200) +
  scale_fill_viridis_c(name = "log(hP9+0.1)", direction = -1) +
  theme(legend.position = "bottom")

# cP9 colour
p4 <- ggplot(forcecalled[zcw_cov_input>5], (aes(zcw_enrichment, zcw_cP9_enrichment, z=log(cP9combo_enrichment+0.1)))) +
  stat_summary_hex(bins=200) +
  scale_fill_viridis_c(name = "log(cP9+0.1)", direction = -1) +
  theme(legend.position = "bottom")


####
# Color by CVC enrichment
####

p1CVC <- ggplot(forcecalled[zcw_cov_input>5], (aes(zcw_enrichment, zcw_hP9_enrichment, z=log(zcw_hCVC_enrichment+0.1)))) +
  stat_summary_hex(bins=200) +
  scale_fill_viridis_c(name = "log(hCVC+0.1)", direction = -1) +
  theme(legend.position = "bottom")

# cP9 colour
p2CVC <- ggplot(forcecalled[zcw_cov_input>5], (aes(zcw_enrichment, zcw_hP9_enrichment, z=log(zcw_cCVC_enrichment+0.1)))) +
  stat_summary_hex(bins=200) +
  scale_fill_viridis_c(name = "log(cCVC+0.1)", direction = -1) +
  theme(legend.position = "bottom")

# hP9 colour
p3CVC <- ggplot(forcecalled[zcw_cov_input>5], (aes(zcw_enrichment, zcw_cP9_enrichment, z=log(zcw_hCVC_enrichment+0.1)))) +
  stat_summary_hex(bins=200) +
  scale_fill_viridis_c(name = "log(hCVC+0.1)", direction = -1) +
  theme(legend.position = "bottom")

# cP9 colour
p4CVC <- ggplot(forcecalled[zcw_cov_input>5], (aes(zcw_enrichment, zcw_cP9_enrichment, z=log(zcw_cCVC_enrichment+0.1)))) +
  stat_summary_hex(bins=200) +
  scale_fill_viridis_c(name = "log(cCVC+0.1)", direction = -1) +
  theme(legend.position = "bottom")



# Arrange & Save plots

pdf(width = 14, height = 14, file = "Zcw_vs_CoTransfection.pdf")
plot_grid(cHP9 + ylim(0,8),
          cHP9 + scale_x_log10(limits=c(0.1,NA)) + scale_y_log10(limits=c(0.1,NA)),
          cCP9 + ylim(0,8),
          cCP9 + scale_x_log10(limits=c(0.1,NA)) + scale_y_log10(limits=c(0.1,NA))
          )

plot_grid(p1 + ylim(0,8), p2 + ylim(0,8), p3 + ylim(0,8), p4 + ylim(0,8))

plot_grid(p1 + scale_x_log10(limits=c(0.1,NA)) + scale_y_log10(limits=c(0.1,NA)),
          p2 + scale_x_log10(limits=c(0.1,NA)) + scale_y_log10(limits=c(0.1,NA)),
          p3 + scale_x_log10(limits=c(0.1,NA)) + scale_y_log10(limits=c(0.1,NA)),
          p4 + scale_x_log10(limits=c(0.1,NA)) + scale_y_log10(limits=c(0.1,NA)))

plot_grid(p1CVC + ylim(0,8), p2CVC + ylim(0,8), p3CVC + ylim(0,8), p4CVC + ylim(0,8))
dev.off()


# Split into definately bound and definately not, for visual clarity

pdf("Zcw_vs_CoTransfection2.pdf")
p1 + ylim(0,8) + gghighlight(hP9combo_pvalue<1e-9, unhighlighted_colour="darkgrey")
p1 + ylim(0,8) + gghighlight(hP9combo_pvalue==1, unhighlighted_colour="darkgrey")

cHP9 + ylim(0,8) + gghighlight(hP9combo_pvalue<1e-9, unhighlighted_colour="darkgrey")
cHP9 + ylim(0,8) + gghighlight(hP9combo_pvalue==1, unhighlighted_colour="darkgrey")

forcecalled[,hP9Combo.bound := NA]
forcecalled[hP9combo_pvalue==1, hP9Combo.bound := FALSE]
forcecalled[hP9combo_pvalue<1e-9, hP9Combo.bound := TRUE]

p1 <- ggplot(forcecalled[zcw_cov_input>5 & hP9combo_cov_input>5][!zcw_enrichment<1e-2 & !zcw_hP9_enrichment<1e-2], (aes(zcw_enrichment, zcw_hP9_enrichment, z=hP9Combo.bound))) +
  #stat_summary_hex(bins=200, alpha=0.5, fun= function(x) as.character(mean(x))) + # na.rm=T
  stat_summary_hex(bins=200, alpha=0.5, fun= function(x)if(length(x)>=3){as.character(mean(x))}else{NA}) + # na.rm=T
  geom_density_2d(aes(colour=hP9Combo.bound),bins=15) +
  labs(x="Enrichment of Zcwpw1", y="Enrichment of Zcwpw1 when cotransfected with human Prdm9") +
  scale_fill_manual(labels = c("p = 1", "p < 10^(-9)"), values = c("#E41A1C", "#377EB8")) +
  scale_colour_manual(values = c("#E41A1C", "#377EB8"), guide=FALSE) +
  labs(fill="Evidence of human Prdm9 binding") +
  theme(legend.position = "bottom") +
  ylim(0,8) + xlim(0,8)

# log scale
p1l <- ggplot(forcecalled[zcw_cov_input>5 & hP9combo_cov_input>5], (aes(log(zcw_enrichment+0.1), log(zcw_hP9_enrichment+0.1), z=hP9Combo.bound))) +
  stat_summary_hex(bins=200, alpha=0.5, fun= function(x) as.character(mean(x))) + # na.rm=T
  #scale_fill_brewer(palette="Set1") +
  scale_fill_manual(labels = c("p = 1", "p < 10^(-9)"), values = c("#E41A1C", "#377EB8")) +
  labs(fill="Evidence of hPrdm9cterm binding") +
  theme(legend.position = "bottom") + 
  xlim(-0.5,NA) + ylim(-0.5, NA)


# CHIMP

#1e-4
forcecalled[,cP9Combo.bound := NA]
forcecalled[cP9combo_pvalue==1, cP9Combo.bound := FALSE]
forcecalled[cP9combo_pvalue<1e-3, cP9Combo.bound := TRUE]

p2 <- ggplot(forcecalled[zcw_cov_input>5 & cP9combo_cov_input>5][!zcw_enrichment<1e-2 & !zcw_cP9_enrichment<1e-2], (aes(zcw_enrichment, zcw_cP9_enrichment, z=cP9Combo.bound))) +
  #stat_summary_hex(bins=200, alpha=0.5, fun= function(x) as.character(mean(x))) + # na.rm=T
  stat_summary_hex(bins=200, alpha=0.5, fun= function(x)if(length(x)>=3){as.character(mean(x))}else{NA}) + # na.rm=T
  geom_density_2d(aes(colour=cP9Combo.bound),bins=15) +
  labs(x="Enrichment of Zcwpw1", y="Enrichment of Zcwpw1 when cotransfected with chimp Prdm9") +
  scale_fill_manual(labels = c("p = 1", "p < 10^(-3)"), values = c("#E41A1C", "#377EB8")) +
  scale_colour_manual(values = c("#E41A1C", "#377EB8"), guide=FALSE) +
  labs(fill="Evidence of chimp Prdm9 binding") +
  theme(legend.position = "bottom") +
  ylim(0,6) + xlim(0,6)


pdf("Zcw_vs_CoTransfection_summary_plot_allchr.pdf", width=12)
plot_grid(p1, p2)
dev.off()


```


# Relative Strength/Attraction of H3K4me3

```{r}

pdf("H3K4strength.pdf")

# K4UT vs K4wP9

p <- ggplot(forcecalled[h3k4me3_UT_cov_input>5 & h3k4me3_hP9_cov_input>5], aes(h3k4me3_UT, h3k4me3_hP9_enrichment)) +
  geom_hex(aes(fill = stat(log(count))), bins=200) +
  scale_fill_viridis_c()

# All & Zoom
p
p + xlim(0,30) + ylim(0,30)

# Colour by Zcw
ggplot(forcecalled[h3k4me3_UT_cov_input>5 & h3k4me3_hP9_cov_input>5], aes(h3k4me3_UT, h3k4me3_hP9_enrichment, z=log(zcw_hP9_enrichment+0.1))) +
  stat_summary_hex(bins=200) + theme(legend.position = "bottom") +
  scale_fill_viridis_c(name = "log(Zcw_w/hP9+0.1)", direction = -1) + xlim(0,30) + ylim(0,30)

# Log scale count
ggplot(forcecalled[h3k4me3_UT_cov_input>5 & h3k4me3_hP9_cov_input>5], aes(log(h3k4me3_UT+0.1), log(h3k4me3_hP9_enrichment+0.1))) +
  geom_hex(aes(fill = stat(log(count))), bins=200) +
  scale_fill_viridis_c() + geom_abline(intercept = 0, slope = 1, col='red')

# Log scale colour by Zcw
ggplot(forcecalled[h3k4me3_UT_cov_input>5 & h3k4me3_hP9_cov_input>5], aes(log(h3k4me3_UT+0.1), log(h3k4me3_hP9_enrichment+0.1), z=log(zcw_hP9_enrichment+0.1))) +
  #stat_summary_hex(bins=200) +
  stat_summary_hex(bins=200, fun= function(x)if(length(x)>=3){mean(x)}else{NA}) +
  theme(legend.position = "bottom") +
  scale_fill_viridis_c(name = "log(Zcw_w/hP9+0.1)", direction = -1)


# Zcw colour, as P9 increases, for a given H3K4
ggplot(forcecalled[zcw_cov_input>5 & hP9combo_cov_input>5 & h3k4me3_hP9_cov_input>5], aes(hP9combo_enrichment, h3k4me3_hP9_enrichment, z=log(zcw_hP9_enrichment+0.1))) +
  stat_summary_hex(bins=200) + theme(legend.position = "bottom") +
  scale_fill_viridis_c(name = "log(Zcw_w/hP9+0.1)", direction = -1) + xlim(0,20) + ylim(0,50) +
  ggtitle("zcw cov input")

# min 3
ggplot(forcecalled[zcw_cov_input>5 & hP9combo_cov_input>5 & h3k4me3_hP9_cov_input>5], aes(log(hP9combo_enrichment+0.1), log(h3k4me3_hP9_enrichment+0.1), z=log(zcw_hP9_enrichment+0.1))) +
  stat_summary_hex(bins=200, fun= function(x)if(length(x)>=3){mean(x)}else{NA}) +
  theme(legend.position = "bottom") +
  scale_fill_viridis_c(name = "log(Zcw_w/hP9+0.1)", direction = -1)

dev.off()
```


# K4 vs Zcw (CT) split by hP9 status

For a given amount of H3K4, Zcw is higher enriched when P9 bound at non promoters than promoters


```{r}

forcecalled[,UTP9 := NULL]
forcecalled[hP9combo_cov_input>5 & hP9combo_pvalue==1, UTP9 := "0"]
forcecalled[hP9combo_cov_input>5 & hP9combo_pvalue<1e-7, UTP9 := "1"]
forcecalled[h3k4me3_UT_cov_input>5 & h3k4me3_UT_pvalue<1e-5, UTP9 := "2"] # this means the above also has condition h3k4me3_UT_pvalue>1e-5

#forcecalled[,mean(zcw_hP9_enrichment),by=UTP9]
#      UTP9        V1
# 1:    0 0.1162629
# 2: <NA> 0.3742038
# 3:    1 2.1501786
# 4:    2 1.8304093


mingroup <- min(forcecalled[,.N,by=UTP9]$N)
stopifnot(mingroup>5e3)
#forcecalled[,.SD[sample(.N, min(1e4,.N))], by = UTP9][,.N,by=UTP9]

p1 <- ggplot(forcecalled[zcw_cov_input>5 & h3k4me3_hP9_cov_input>5][,.SD[sample(.N, min(mingroup,.N))], by = UTP9], (aes(log(h3k4me3_hP9_enrichment+0.1), log(zcw_hP9_enrichment+0.1), group=UTP9, z=as.numeric(UTP9))))

p2 <- ggplot(forcecalled[zcw_cov_input>5 & h3k4me3_UT_cov_input>5][,.SD[sample(.N, min(mingroup,.N))], by = UTP9], (aes(log(h3k4me3_UT_enrichment+0.1), log(zcw_enrichment+0.1), group=UTP9, z=as.numeric(UTP9))))

p3 <- ggplot(forcecalled[zcw_cov_input>5 & h3k4me3_hP9_cov_input>5][,.SD[sample(.N, min(mingroup,.N))], by = UTP9], (aes(log(h3k4me3_hP9_enrichment+0.1), log(zcw_enrichment+0.1), group=UTP9, z=as.numeric(UTP9))))

p4 <- ggplot(forcecalled[zcw_cov_input>5 & h3k4me3_UT_cov_input>5][,.SD[sample(.N, min(mingroup,.N))], by = UTP9], (aes(log(h3k4me3_UT_enrichment+0.1), log(zcw_hP9_enrichment+0.1), group=UTP9, z=as.numeric(UTP9)))) #+

commongrobs <- list(
  stat_summary_hex(bins=150, alpha=0.5, fun= function(x) if(length(x)>=5){as.character(mean(x))}else{NA}), # duplicate this line for multi-alpha density shading?
  geom_density_2d(aes(colour=UTP9)),
  theme(legend.position = "bottom"),
  scale_fill_manual(labels = c("Not humanPRDM9 bound (p=1)",
                               "humanPRDM9 bound (p<1e-7) & No Untransfected H3K4me3 (p>1e-5)",
                               "Untransfected H3K4me3 (p<1e-5)"),
                    values = RColorBrewer::brewer.pal(3, "Set1"), 
                    name = "Subset"),
  scale_colour_manual(values = RColorBrewer::brewer.pal(3, "Set1"), guide=FALSE),
  xlim(NA,4),
  ylim(NA,2.5)
)

# Count density
# 
# commongrobsCount <- list(
#   #stat_summary_hex(aes(group=1), bins=200, fun= function(x) if(length(x)>=1){log(length(x))}else{NA}),
#   geom_hex(aes(fill = stat(log(count))), bins=200),
#   scale_fill_viridis_c(direction = -1),
#   theme(legend.position = "bottom"),
#   xlim(NA,4),
#   ylim(NA,2.5)
# )
# 
# p1 + commongrobsCount
# dev.off()

pmain <- plot_grid(p1 + commongrobs + theme(legend.position = "none") + labs(title="Transfected vs Cotransfected",
                                                                             x="ln(0.1 + Enrichment of H3K4me3 in humanPRDM9 transfection)", 
                                                                             y="ln(0.1 + Enrichment of Zcwpw1 in Zcwpw1-humanPrdm9 cotransfection)"),
          p3 + commongrobs + theme(legend.position = "none") + labs(title="Transfected vs Singly-transfected",
                                                                             x="ln(0.1 + Enrichment of H3K4me3 in humanPRDM9 transfection)", 
                                                                             y="ln(0.1 + Enrichment of Zcwpw1 in Zcwpw1 single transfection)"),
          p4 + commongrobs + theme(legend.position = "none") + labs(title="Un-transfected vs Cotransfected",
                                                                             x="ln(0.1 + Enrichment of H3K4me3 in untransfected)", 
                                                                             y="ln(0.1 + Enrichment of Zcwpw1 in Zcwpw1-humanPrdm9 cotransfection)"),
          p2 + commongrobs + theme(legend.position = "none") + labs(title="Un-transfected vs Singly-transfected",
                                                                             x="ln(0.1 + Enrichment of H3K4me3 in untransfected)", 
                                                                             y="ln(0.1 + Enrichment of Zcwpw1 in Zcwpw1 single transfection)"))

pdf("H3K4strength_allchr.pdf", width = 14, height = 14)
plot_grid(pmain, get_legend(p1 + commongrobs), ncol=1, rel_heights = c(1, 0.05))
dev.off()

```


## Mean by bin

```{r}

fraction_overlapN <- function(dt,x,y, n=25, filters=c("All"), returndf=F, pseudoenrich=0.01){
  setorder(dt, enrichment)
  dt$enrichment_bin <- cut(1:nrow(dt), n)
  
  All=TRUE
  
  tmp <- dt[eval(parse(text=filters[1])),.(mean_enrichment = mean(enrichment + pseudoenrich),
                                      num = .N,
                                      Mean = mean(get(y)),
                                      Subset = filters[1],
                                      sem = sd(get(y))/sqrt(length(get(y))),
                                      max = max(get(y)),
                                      min = min(get(y)),
                                      uq = quantile(get(y), 0.75),
                                      lq = quantile(get(y), 0.25)
                                      #sep=sqrt((mean(get(y)) * (1- mean(get(y))))/length(get(y)))
                                      ),by=enrichment_bin]

    if(returndf){
    return(tmp)
  }else{
  return(
    ggplot(tmp, aes(mean_enrichment, Mean, colour=Subset, group=Subset)) + #mean_enrichment
      #geom_hline(yintercept = dt[,mean(get(y))], colour="blue", linetype="dashed") +
      geom_point(size=2, stroke=0) +
      geom_linerange(aes(ymax = Mean+2*sem, ymin = Mean-2*sem), colour='black') +
      theme_minimal() +
      scale_color_brewer(palette = 'Set1') +
      xlab(paste("Mean",x,"Enrichment")) +
      ylab(paste("Mean",y))
  )}

}

forcecalled$enrichment <- forcecalled$h3k4me3_hP9_enrichment

pdf("H3K4strength_binned_allchr.pdf")

fraction_overlapN(forcecalled[h3k4me3_hP9_cov_input>5 & zcw_cov_input>5], 
                    "h3k4me3_hP9_enrichment","zcw_hP9_enrichment", n=25) + scale_x_log10()


tmp <- rbind(
  fraction_overlapN(forcecalled[h3k4me3_hP9_cov_input>15 & zcw_cov_input>5][UTP9==1], 
                    "h3k4me3_hP9_enrichment","zcw_hP9_enrichment", n=25, returndf = T, filter="UTP9==1"),
  fraction_overlapN(forcecalled[h3k4me3_hP9_cov_input>15 & zcw_cov_input>5][UTP9==2], 
                    "h3k4me3_hP9_enrichment","zcw_hP9_enrichment", n=25, returndf = T, filter="UTP9==2")
)


ggplot(tmp, aes(mean_enrichment, Mean, colour=Subset)) +
  geom_point() +
  scale_x_log10() +
  xlab("Mean H3K4me3 enrichment in humanPRDM9 transfection") +
  ylab("Mean Zcwpw1 enrichment in Zcwpw1-humanPRDM9 cotransfection") +
  geom_pointrange(aes(ymax = uq, ymin = lq)) +
  geom_errorbar(aes(ymax = Mean + 2*sem, ymin = Mean - 2*sem), width = 0.05) +
  scale_colour_manual(labels = c("humanPRDM9 bound (p<1e-7) & No Untransfected H3K4me3 (p>1e-5)",
                               "Untransfected H3K4me3 (p<1e-5)"),
                      guide=guide_legend(nrow=2),
                    values = RColorBrewer::brewer.pal(3, "Set1")) +
  theme_minimal() +
  theme(legend.position = "bottom")
dev.off()

```


# Zcw ST vs CT binned

```{r}
forcecalled$enrichment <- forcecalled$zcw_enrichment

pdf("Zcw_ST_vs_CT_binned.pdf")

fraction_overlapN(forcecalled[zcw_cov_input>5], 
                    "zcw_enrichment","zcw_hP9_enrichment", n=25)


tmp <- rbind(
  fraction_overlapN(forcecalled[hP9combo_cov_input>5 & zcw_cov_input>5][hP9combo_pvalue==1], 
                    "zcw_enrichment","zcw_hP9_enrichment", n=25, returndf = T, filter="hP9combo_pvalue==1"),
  fraction_overlapN(forcecalled[hP9combo_cov_input>5 & zcw_cov_input>5][hP9combo_pvalue<1e-9], 
                    "zcw_enrichment","zcw_hP9_enrichment", n=25, returndf = T, filter="hP9combo_pvalue<1e-9")
)


ggplot(tmp, aes(mean_enrichment, Mean, colour=Subset)) +
  geom_point() +
  xlab("Mean zcw_enrichment") +
  ylab("Mean zcw_hP9_enrichment") +
  geom_pointrange(aes(ymax = uq, ymin = lq)) +
  geom_errorbar(aes(ymax = Mean + 2*sem, ymin = Mean - 2*sem), width = 0.05) +
  scale_colour_manual(labels = c("hP9combo_pvalue==1",
                               "hP9combo_pvalue<1e-9"),
                    values = RColorBrewer::brewer.pal(3, "Set1")) +
  theme_minimal() +
  theme(legend.position = "bottom")
dev.off()

```

# H3K36

```{r}
forcecalled$enrichment <- forcecalled$h3k36me3_hP9_enrichment

pdf("H3K36.pdf")
fraction_overlapN(forcecalled[hP9combo_cov_input>5 & zcw_cov_input>5], 
                    "h3k36me3_hP9_enrichment","zcw_hP9_enrichment", n=25)
dev.off()

```

# K36wP9 vs K4wP9

```{r}
p <- ggplot(forcecalled[h3k36me3_hP9_enrichment>5], aes(h3k36me3_hP9_enrichment, h3k4me3_hP9_enrichment)) +
  geom_hex(aes(fill = stat(log(count))), bins=200) +
  scale_fill_viridis_c()

p + facet_wrap(~ zcw_P9_pvalue<1e-6 ) + ggtitle("Split by zcw_P9_pvalue<1e-6")


# K4UT vs Zcw
ggplot(forcecalled[h3k4me3_UT>5], aes(h3k4me3_UT, zcw_enrichment)) +
  geom_hex(aes(fill = stat(log(count))), bins=200) +
  scale_fill_viridis_c() + 
  ylim(0,10) + xlim(0,100)

# K4UT vs Zcw w/ hP9
ggplot(forcecalled[h3k4me3_UT>5], aes(h3k4me3_UT, zcw_hP9_enrichment)) +
  geom_hex(aes(fill = stat(log(count))), bins=200) +
  scale_fill_viridis_c() + 
  ylim(0,10) + xlim(0,100)

# K4UT vs P9
p <- ggplot(forcecalled[h3k4me3_UT>5], aes(h3k4me3_UT, hP9combo_enrichment)) +
  geom_hex(aes(fill = stat(log(count))), bins=200) +
  scale_fill_viridis_c() + xlim(0,100)

p + facet_wrap(~ zcw_P9_pvalue<1e-6 ) + ggtitle("Split by zcw_P9_pvalue<1e-6") + 
  ylim(0,15)

p + facet_wrap(~ zcw_enrichment>1 ) + ggtitle("Split by zcw_enrichment>1") + 
  ylim(0,15)

dev.off()

```

