---
title: "In Vitro Peak Calling"
output: html_notebook
---


# Peak Calling


```{r}

export PYTHONPATH=/homes/wells/python/:$PYTHONPATH
pip install --user MACS2
find / -name macs2
export PATH=/homes/wells/.local/bin:$PATH

```

# Chip Z vs Input

```{r}
# 220144 In_ZHA_hP9V5
# 223180 ChpHA_ZHA_hP9V5

macs2 callpeak \
  -t higcovfiltered/223180.bam \
  -c higcovfiltered/220144.bam \
  -f BAMPE \
  -g hs \
  -n ${expid}_ChpHA_ZHA_hP9V5 \
  --outdir macs \
  -B \
  -q 0.01 2> macs/${expid}_ChpHA_ZHA_hP9V5.log

Rscript 538916_ChpHA_ZHA_hP9V5_model.r

```

```{r}
macs_peaks <- fread("../data/macs/538916_ChpHA_ZHA_hP9V5_peaks.xls")
names(macs_peaks) <- make.names(names(macs_peaks))
str(macs_peaks)
macs_peaks[order(-X.log10.pvalue.)][1:10]
macs_peaks[order(-X.log10.pvalue.)][1:300][,.(paste0(chr,":",start,"-",end))]
```


```{r}
fwrite(macs_peaks2[order(-V9)][V2>5001][1:100][,.(V1, V2-5000, V3+5000)], "data/macs/macs_peaks_top100.bed", col.names = FALSE, sep = "\t")

# 220144 In_ZHA_hP9V5
# 223180 ChpHA_ZHA_hP9V5


for sample in 220144 223180
do
(
samtools view higcovfiltered/${sample}.bam -L beds/macs_peaks_top100.bed -b -o sample_regions/sample_${expid}_${sample}_macstop100.bam
samtools index sample_regions/sample_${expid}_${sample}_macstop100.bam
) &
done

```

# Chip with vs without Prdm9

```{r}
# 221156 ChpHA_ZHA vs 223180 ChpHA_ZHA_hP9V5

macs2 callpeak \
  -t higcovfiltered/223180.bam \
  -c higcovfiltered/221156.bam \
  -f BAMPE \
  -g hs \
  -n 538916_ChpHA_ZHA_hP9V5_vs_ChpHA_ZHA \
  --outdir macs \
  -B \
  -q 0.01 2> macs/538916_ChpHA_ZHA_hP9V5_vs_ChpHA_ZHA.log

```

```{r}
macs_peaks <- fread("../data/macs/538916_ChpHA_ZHA_hP9V5_vs_ChpHA_ZHA_peaks.xls")
names(macs_peaks) <- make.names(names(macs_peaks))
str(macs_peaks)
macs_peaks[order(-X.log10.pvalue.)][1:100]
macs_peaks[order(-X.log10.pvalue.)][1:300][,.(paste0(chr,":",start,"-",end))]
```


```{r}
fwrite(macs_peaks[order(-X.log10.pvalue.)][start>5001][1:100][,.(chr, start-5000, end+5000)], "data/macs/macs_peaks_top100_induced.bed", col.names = FALSE, sep = "\t")


for sample in 221156 223180
do
(
samtools view higcovfiltered/${sample}.bam -L beds/macs_peaks_top100_induced.bed -b -o sample_regions/sample_${expid}_${sample}_macstop100_induced.bam
samtools index sample_regions/sample_${expid}_${sample}_macstop100_induced.bam
) &
done

```

